# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\jayden\projects\FeedbackAssistant\assisant.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FeedbackAssistant(object):
    def setupUi(self, FeedbackAssistant):
        FeedbackAssistant.setObjectName("FeedbackAssistant")
        FeedbackAssistant.resize(1114, 896)
        self.centralwidget = QtWidgets.QWidget(FeedbackAssistant)
        self.centralwidget.setObjectName("centralwidget")
        self.table_hw = QtWidgets.QTableWidget(self.centralwidget)
        self.table_hw.setGeometry(QtCore.QRect(20, 50, 601, 171))
        self.table_hw.setObjectName("table_hw")
        self.table_hw.setColumnCount(0)
        self.table_hw.setRowCount(0)
        self.display = QtWidgets.QTextBrowser(self.centralwidget)
        self.display.setGeometry(QtCore.QRect(730, 20, 371, 821))
        self.display.setReadOnly(False)
        self.display.setObjectName("display")
        self.table_ip = QtWidgets.QTableWidget(self.centralwidget)
        self.table_ip.setGeometry(QtCore.QRect(20, 510, 601, 171))
        self.table_ip.setObjectName("table_ip")
        self.table_ip.setColumnCount(0)
        self.table_ip.setRowCount(0)
        self.table_pf = QtWidgets.QTableWidget(self.centralwidget)
        self.table_pf.setGeometry(QtCore.QRect(20, 280, 601, 171))
        self.table_pf.setObjectName("table_pf")
        self.table_pf.setColumnCount(0)
        self.table_pf.setRowCount(0)
        self.label_homework = QtWidgets.QLabel(self.centralwidget)
        self.label_homework.setGeometry(QtCore.QRect(20, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_homework.setFont(font)
        self.label_homework.setObjectName("label_homework")
        self.label_performance = QtWidgets.QLabel(self.centralwidget)
        self.label_performance.setGeometry(QtCore.QRect(20, 250, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_performance.setFont(font)
        self.label_performance.setObjectName("label_performance")
        self.label_improvement = QtWidgets.QLabel(self.centralwidget)
        self.label_improvement.setGeometry(QtCore.QRect(20, 480, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_improvement.setFont(font)
        self.label_improvement.setObjectName("label_improvement")
        self.button_hw = QtWidgets.QPushButton(self.centralwidget)
        self.button_hw.setGeometry(QtCore.QRect(640, 110, 75, 61))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_hw.setFont(font)
        self.button_hw.setObjectName("button_hw")
        self.button_ip = QtWidgets.QPushButton(self.centralwidget)
        self.button_ip.setGeometry(QtCore.QRect(640, 560, 75, 61))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_ip.setFont(font)
        self.button_ip.setObjectName("button_ip")
        self.button_pf = QtWidgets.QPushButton(self.centralwidget)
        self.button_pf.setGeometry(QtCore.QRect(640, 340, 75, 61))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_pf.setFont(font)
        self.button_pf.setObjectName("button_pf")
        self.button_edit = QtWidgets.QPushButton(self.centralwidget)
        self.button_edit.setGeometry(QtCore.QRect(20, 700, 151, 41))
        self.button_edit.setObjectName("button_edit")
        FeedbackAssistant.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(FeedbackAssistant)
        self.statusbar.setAccessibleName("")
        self.statusbar.setObjectName("statusbar")
        FeedbackAssistant.setStatusBar(self.statusbar)

        self.retranslateUi(FeedbackAssistant)
        QtCore.QMetaObject.connectSlotsByName(FeedbackAssistant)

    def retranslateUi(self, FeedbackAssistant):
        _translate = QtCore.QCoreApplication.translate
        FeedbackAssistant.setWindowTitle(_translate("FeedbackAssistant", "FeedbackAssistant"))
        self.label_homework.setText(_translate("FeedbackAssistant", "Homework"))
        self.label_performance.setText(_translate("FeedbackAssistant", "Performance"))
        self.label_improvement.setText(_translate("FeedbackAssistant", "Improvement"))
        self.button_hw.setText(_translate("FeedbackAssistant", ">>"))
        self.button_ip.setText(_translate("FeedbackAssistant", ">>"))
        self.button_pf.setText(_translate("FeedbackAssistant", ">>"))
        self.button_edit.setText(_translate("FeedbackAssistant", "Edit"))

