# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\jayden\projects\FeedbackAssistant\ui\assistant.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FeedbackAssistant(object):
    def setupUi(self, FeedbackAssistant):
        FeedbackAssistant.setObjectName("FeedbackAssistant")
        FeedbackAssistant.setWindowModality(QtCore.Qt.NonModal)
        FeedbackAssistant.resize(1114, 932)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        FeedbackAssistant.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(FeedbackAssistant)
        self.centralwidget.setObjectName("centralwidget")
        self.table_hw = QtWidgets.QTableWidget(self.centralwidget)
        self.table_hw.setGeometry(QtCore.QRect(20, 50, 601, 171))
        self.table_hw.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_hw.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.table_hw.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_hw.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.table_hw.setWordWrap(False)
        self.table_hw.setColumnCount(1)
        self.table_hw.setObjectName("table_hw")
        self.table_hw.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_hw.setHorizontalHeaderItem(0, item)
        self.table_hw.horizontalHeader().setStretchLastSection(True)
        self.table_hw.verticalHeader().setCascadingSectionResizes(False)
        self.table_hw.verticalHeader().setHighlightSections(True)
        self.display = QtWidgets.QTextBrowser(self.centralwidget)
        self.display.setGeometry(QtCore.QRect(730, 20, 371, 871))
        self.display.setUndoRedoEnabled(True)
        self.display.setReadOnly(False)
        self.display.setObjectName("display")
        self.table_ipv = QtWidgets.QTableWidget(self.centralwidget)
        self.table_ipv.setGeometry(QtCore.QRect(20, 510, 601, 171))
        self.table_ipv.setMidLineWidth(0)
        self.table_ipv.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_ipv.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.table_ipv.setColumnCount(1)
        self.table_ipv.setObjectName("table_ipv")
        self.table_ipv.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_ipv.setHorizontalHeaderItem(0, item)
        self.table_ipv.horizontalHeader().setStretchLastSection(True)
        self.table_ipv.verticalHeader().setCascadingSectionResizes(False)
        self.table_pfm = QtWidgets.QTableWidget(self.centralwidget)
        self.table_pfm.setGeometry(QtCore.QRect(20, 280, 601, 171))
        self.table_pfm.setLineWidth(1)
        self.table_pfm.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_pfm.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.table_pfm.setColumnCount(1)
        self.table_pfm.setObjectName("table_pfm")
        self.table_pfm.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_pfm.setHorizontalHeaderItem(0, item)
        self.table_pfm.horizontalHeader().setStretchLastSection(True)
        self.table_pfm.verticalHeader().setVisible(True)
        self.table_pfm.verticalHeader().setHighlightSections(True)
        self.label_homework = QtWidgets.QLabel(self.centralwidget)
        self.label_homework.setGeometry(QtCore.QRect(20, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_homework.setFont(font)
        self.label_homework.setObjectName("label_homework")
        self.label_performance = QtWidgets.QLabel(self.centralwidget)
        self.label_performance.setGeometry(QtCore.QRect(20, 250, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_performance.setFont(font)
        self.label_performance.setObjectName("label_performance")
        self.label_improvement = QtWidgets.QLabel(self.centralwidget)
        self.label_improvement.setGeometry(QtCore.QRect(20, 480, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_improvement.setFont(font)
        self.label_improvement.setObjectName("label_improvement")
        self.button_append = QtWidgets.QPushButton(self.centralwidget)
        self.button_append.setGeometry(QtCore.QRect(640, 190, 75, 351))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_append.setFont(font)
        self.button_append.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/imageedit_13_8116585645.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_append.setIcon(icon1)
        self.button_append.setIconSize(QtCore.QSize(70, 300))
        self.button_append.setObjectName("button_append")
        self.button_delete = QtWidgets.QPushButton(self.centralwidget)
        self.button_delete.setGeometry(QtCore.QRect(180, 700, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.button_delete.setFont(font)
        self.button_delete.setObjectName("button_delete")
        self.button_redo = QtWidgets.QPushButton(self.centralwidget)
        self.button_redo.setGeometry(QtCore.QRect(660, 840, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_redo.setFont(font)
        self.button_redo.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/Redo-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_redo.setIcon(icon2)
        self.button_redo.setIconSize(QtCore.QSize(31, 31))
        self.button_redo.setObjectName("button_redo")
        self.button_undo = QtWidgets.QPushButton(self.centralwidget)
        self.button_undo.setGeometry(QtCore.QRect(660, 780, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_undo.setFont(font)
        self.button_undo.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/Undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_undo.setIcon(icon3)
        self.button_undo.setIconSize(QtCore.QSize(31, 31))
        self.button_undo.setObjectName("button_undo")
        self.button_add = QtWidgets.QPushButton(self.centralwidget)
        self.button_add.setGeometry(QtCore.QRect(20, 700, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.button_add.setFont(font)
        self.button_add.setObjectName("button_add")
        self.button_copy = QtWidgets.QPushButton(self.centralwidget)
        self.button_copy.setGeometry(QtCore.QRect(660, 690, 61, 61))
        self.button_copy.setToolTipDuration(-1)
        self.button_copy.setStatusTip("")
        self.button_copy.setWhatsThis("")
        self.button_copy.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/copy2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_copy.setIcon(icon4)
        self.button_copy.setIconSize(QtCore.QSize(41, 41))
        self.button_copy.setObjectName("button_copy")
        self.label_copy = QtWidgets.QLabel(self.centralwidget)
        self.label_copy.setGeometry(QtCore.QRect(660, 750, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_copy.setFont(font)
        self.label_copy.setText("")
        self.label_copy.setAlignment(QtCore.Qt.AlignCenter)
        self.label_copy.setObjectName("label_copy")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 800, 71, 71))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/icon.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.button_append_redo = QtWidgets.QPushButton(self.centralwidget)
        self.button_append_redo.setGeometry(QtCore.QRect(650, 610, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_append_redo.setFont(font)
        self.button_append_redo.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/1206569942771180767pitr_green_double_arrows_set_1.svg.hi.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_append_redo.setIcon(icon5)
        self.button_append_redo.setIconSize(QtCore.QSize(35, 35))
        self.button_append_redo.setObjectName("button_append_redo")
        self.button_append_undo = QtWidgets.QPushButton(self.centralwidget)
        self.button_append_undo.setGeometry(QtCore.QRect(650, 550, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_append_undo.setFont(font)
        self.button_append_undo.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/1206569967984704715pitr_green_double_arrows_set_4.svg.hi.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_append_undo.setIcon(icon6)
        self.button_append_undo.setIconSize(QtCore.QSize(35, 35))
        self.button_append_undo.setObjectName("button_append_undo")
        FeedbackAssistant.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(FeedbackAssistant)
        self.statusbar.setAccessibleName("")
        self.statusbar.setObjectName("statusbar")
        FeedbackAssistant.setStatusBar(self.statusbar)

        self.retranslateUi(FeedbackAssistant)
        QtCore.QMetaObject.connectSlotsByName(FeedbackAssistant)

    def retranslateUi(self, FeedbackAssistant):
        _translate = QtCore.QCoreApplication.translate
        FeedbackAssistant.setWindowTitle(_translate("FeedbackAssistant", "FeedbackAssistant"))
        item = self.table_hw.horizontalHeaderItem(0)
        item.setText(_translate("FeedbackAssistant", "Content"))
        item = self.table_ipv.horizontalHeaderItem(0)
        item.setText(_translate("FeedbackAssistant", "Content"))
        item = self.table_pfm.horizontalHeaderItem(0)
        item.setText(_translate("FeedbackAssistant", "Content"))
        self.label_homework.setText(_translate("FeedbackAssistant", "Homework"))
        self.label_performance.setText(_translate("FeedbackAssistant", "Performance"))
        self.label_improvement.setText(_translate("FeedbackAssistant", "Improvement"))
        self.button_append.setToolTip(_translate("FeedbackAssistant", "Append"))
        self.button_append.setShortcut(_translate("FeedbackAssistant", "Alt+A"))
        self.button_delete.setToolTip(_translate("FeedbackAssistant", "Delete a feedback"))
        self.button_delete.setText(_translate("FeedbackAssistant", "Delete"))
        self.button_redo.setToolTip(_translate("FeedbackAssistant", "Redo"))
        self.button_undo.setToolTip(_translate("FeedbackAssistant", "Undo"))
        self.button_add.setToolTip(_translate("FeedbackAssistant", "Add a feedback"))
        self.button_add.setText(_translate("FeedbackAssistant", "Add"))
        self.button_copy.setToolTip(_translate("FeedbackAssistant", "Copy to clipboard"))
        self.button_append_redo.setToolTip(_translate("FeedbackAssistant", "Undo"))
        self.button_append_undo.setToolTip(_translate("FeedbackAssistant", "Undo"))

import assistant_rc
