# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\assistant_v2.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FeedbackAssistant(object):
    def setupUi(self, FeedbackAssistant):
        FeedbackAssistant.setObjectName("FeedbackAssistant")
        FeedbackAssistant.setWindowModality(QtCore.Qt.NonModal)
        FeedbackAssistant.resize(1114, 752)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FeedbackAssistant.sizePolicy().hasHeightForWidth())
        FeedbackAssistant.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        FeedbackAssistant.setWindowIcon(icon)
        FeedbackAssistant.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(FeedbackAssistant)
        self.centralwidget.setObjectName("centralwidget")
        self.display = QtWidgets.QTextBrowser(self.centralwidget)
        self.display.setGeometry(QtCore.QRect(630, 20, 471, 701))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.display.setFont(font)
        self.display.setUndoRedoEnabled(True)
        self.display.setReadOnly(False)
        self.display.setObjectName("display")
        self.button_delete = QtWidgets.QPushButton(self.centralwidget)
        self.button_delete.setGeometry(QtCore.QRect(40, 650, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.button_delete.setFont(font)
        self.button_delete.setObjectName("button_delete")
        self.button_redo = QtWidgets.QPushButton(self.centralwidget)
        self.button_redo.setGeometry(QtCore.QRect(1050, 670, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_redo.setFont(font)
        self.button_redo.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/Redo-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_redo.setIcon(icon1)
        self.button_redo.setIconSize(QtCore.QSize(21, 21))
        self.button_redo.setObjectName("button_redo")
        self.button_undo = QtWidgets.QPushButton(self.centralwidget)
        self.button_undo.setGeometry(QtCore.QRect(1000, 670, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_undo.setFont(font)
        self.button_undo.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/Undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_undo.setIcon(icon2)
        self.button_undo.setIconSize(QtCore.QSize(21, 21))
        self.button_undo.setObjectName("button_undo")
        self.button_add = QtWidgets.QPushButton(self.centralwidget)
        self.button_add.setGeometry(QtCore.QRect(40, 600, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.button_add.setFont(font)
        self.button_add.setObjectName("button_add")
        self.button_copy = QtWidgets.QPushButton(self.centralwidget)
        self.button_copy.setGeometry(QtCore.QRect(470, 610, 61, 61))
        self.button_copy.setToolTipDuration(-1)
        self.button_copy.setStatusTip("")
        self.button_copy.setWhatsThis("")
        self.button_copy.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/copy2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_copy.setIcon(icon3)
        self.button_copy.setIconSize(QtCore.QSize(41, 41))
        self.button_copy.setObjectName("button_copy")
        self.label_copy = QtWidgets.QLabel(self.centralwidget)
        self.label_copy.setGeometry(QtCore.QRect(470, 670, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_copy.setFont(font)
        self.label_copy.setText("")
        self.label_copy.setAlignment(QtCore.Qt.AlignCenter)
        self.label_copy.setObjectName("label_copy")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 600, 91, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/icon.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.button_append_redo = QtWidgets.QPushButton(self.centralwidget)
        self.button_append_redo.setGeometry(QtCore.QRect(550, 670, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_append_redo.setFont(font)
        self.button_append_redo.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/1206569942771180767pitr_green_double_arrows_set_1.svg.hi.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_append_redo.setIcon(icon4)
        self.button_append_redo.setIconSize(QtCore.QSize(35, 35))
        self.button_append_redo.setObjectName("button_append_redo")
        self.button_append_undo = QtWidgets.QPushButton(self.centralwidget)
        self.button_append_undo.setGeometry(QtCore.QRect(550, 610, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_append_undo.setFont(font)
        self.button_append_undo.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/1206569967984704715pitr_green_double_arrows_set_4.svg.hi.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_append_undo.setIcon(icon5)
        self.button_append_undo.setIconSize(QtCore.QSize(35, 35))
        self.button_append_undo.setObjectName("button_append_undo")
        self.content = QtWidgets.QTabWidget(self.centralwidget)
        self.content.setGeometry(QtCore.QRect(10, 20, 601, 571))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.content.setFont(font)
        self.content.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.content.setMouseTracking(True)
        self.content.setStyleSheet("QTabBar::tab { height: 120px;}")
        self.content.setTabPosition(QtWidgets.QTabWidget.West)
        self.content.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.content.setIconSize(QtCore.QSize(25, 25))
        self.content.setElideMode(QtCore.Qt.ElideNone)
        self.content.setTabBarAutoHide(False)
        self.content.setObjectName("content")
        self.tab_hw = QtWidgets.QWidget()
        self.tab_hw.setObjectName("tab_hw")
        self.table_hw = QtWidgets.QTableWidget(self.tab_hw)
        self.table_hw.setGeometry(QtCore.QRect(0, 0, 581, 571))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.table_hw.setFont(font)
        self.table_hw.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.table_hw.setStyleSheet("QTableWidget::item:hover {background-color: #faf7ff; color: black}")
        self.table_hw.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_hw.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.table_hw.setObjectName("table_hw")
        self.table_hw.setColumnCount(1)
        self.table_hw.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(False)
        item.setFont(font)
        self.table_hw.setHorizontalHeaderItem(0, item)
        self.table_hw.horizontalHeader().setStretchLastSection(True)
        self.table_hw.verticalHeader().setDefaultSectionSize(35)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/alphabet-h-letter-letters-red.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.content.addTab(self.tab_hw, icon6, "")
        self.tab_pfm = QtWidgets.QWidget()
        self.tab_pfm.setObjectName("tab_pfm")
        self.table_pfm = QtWidgets.QTableWidget(self.tab_pfm)
        self.table_pfm.setGeometry(QtCore.QRect(0, 0, 581, 591))
        self.table_pfm.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.table_pfm.setStyleSheet("QTableWidget::item:hover {background-color: #faf7ff; color: black}")
        self.table_pfm.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_pfm.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.table_pfm.setObjectName("table_pfm")
        self.table_pfm.setColumnCount(1)
        self.table_pfm.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.table_pfm.setHorizontalHeaderItem(0, item)
        self.table_pfm.horizontalHeader().setStretchLastSection(True)
        self.table_pfm.verticalHeader().setDefaultSectionSize(35)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/alphabet-letter-letters-p-red.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.content.addTab(self.tab_pfm, icon7, "")
        self.tab_ipv = QtWidgets.QWidget()
        self.tab_ipv.setObjectName("tab_ipv")
        self.table_ipv = QtWidgets.QTableWidget(self.tab_ipv)
        self.table_ipv.setGeometry(QtCore.QRect(0, 0, 581, 591))
        self.table_ipv.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.table_ipv.setStyleSheet("QTableWidget::item:hover {background-color: #faf7ff; color: black}")
        self.table_ipv.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_ipv.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.table_ipv.setObjectName("table_ipv")
        self.table_ipv.setColumnCount(1)
        self.table_ipv.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.table_ipv.setHorizontalHeaderItem(0, item)
        self.table_ipv.horizontalHeader().setStretchLastSection(True)
        self.table_ipv.verticalHeader().setDefaultSectionSize(35)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/letter.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.content.addTab(self.tab_ipv, icon8, "")
        self.button_clear = QtWidgets.QPushButton(self.centralwidget)
        self.button_clear.setGeometry(QtCore.QRect(950, 670, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_clear.setFont(font)
        self.button_clear.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/Cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_clear.setIcon(icon9)
        self.button_clear.setIconSize(QtCore.QSize(21, 21))
        self.button_clear.setObjectName("button_clear")
        FeedbackAssistant.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(FeedbackAssistant)
        self.statusbar.setAccessibleName("")
        self.statusbar.setObjectName("statusbar")
        FeedbackAssistant.setStatusBar(self.statusbar)

        self.retranslateUi(FeedbackAssistant)
        self.content.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FeedbackAssistant)

    def retranslateUi(self, FeedbackAssistant):
        _translate = QtCore.QCoreApplication.translate
        FeedbackAssistant.setWindowTitle(_translate("FeedbackAssistant", "FeedbackAssistant"))
        self.button_delete.setToolTip(_translate("FeedbackAssistant", "Delete a feedback"))
        self.button_delete.setText(_translate("FeedbackAssistant", "Delete"))
        self.button_redo.setToolTip(_translate("FeedbackAssistant", "Redo"))
        self.button_undo.setToolTip(_translate("FeedbackAssistant", "Undo"))
        self.button_add.setToolTip(_translate("FeedbackAssistant", "Add a feedback"))
        self.button_add.setText(_translate("FeedbackAssistant", "Add"))
        self.button_copy.setToolTip(_translate("FeedbackAssistant", "Copy to clipboard"))
        self.label.setToolTip(_translate("FeedbackAssistant", "I love LTT"))
        self.button_append_redo.setToolTip(_translate("FeedbackAssistant", "Redo append"))
        self.button_append_undo.setToolTip(_translate("FeedbackAssistant", "Undo append"))
        item = self.table_hw.horizontalHeaderItem(0)
        item.setText(_translate("FeedbackAssistant", "Homework"))
        item = self.table_pfm.horizontalHeaderItem(0)
        item.setText(_translate("FeedbackAssistant", "Performance"))
        item = self.table_ipv.horizontalHeaderItem(0)
        item.setText(_translate("FeedbackAssistant", "Improvement"))
        self.button_clear.setToolTip(_translate("FeedbackAssistant", "Clear text"))

import assistant_rc
